(eval-when-compile    (require 'color-theme))
(defun color-theme-terminal ()
  "Color theme by Leon Waldman, created 2013-05-08."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "unspecified-bg")
      (background-mode . dark)
      (cursor-color . "black")
      (foreground-color . "unspecified-fg"))
     ;; ((ac-fuzzy-cursor-color . "red")
     ;;  (compilation-message-face . underline)
     ;;  (hl-line-face . hl-line)
     ;;  (list-matching-lines-buffer-name-face . underline)
     ;;  (list-matching-lines-face . match)
     ;;  (view-highlight-face . highlight)
     ;;  (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-selection-face ((t (:background "steelblue" :foreground "white"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "cyan"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:foreground "green"))))
     (compilation-error ((t (:foreground "red"))))
     (compilation-info ((t (:bold t :weight bold :foreground "green"))))
     (compilation-line-number ((t (:bold t :weight bold :foreground "cyan"))))
     (compilation-warning ((t (:bold t :weight bold :foreground "yellow"))))
     (completions-annotations ((t (:underline t))))
     (completions-common-part ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :height 1))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "white"))))
     (error ((t (:foreground "red"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (evil-ex-info ((t (:italic t :foreground "red" :slant italic))))
     (evil-ex-lazy-highlight ((t (:background "turquoise3"))))
     (evil-ex-search ((t (:foreground "cyan1" :background "magenta4"))))
     (evil-ex-substitute-matches ((t (:background "turquoise3"))))
     (evil-ex-substitute-replacement ((t (:foreground "red" :underline t))))
     (file-name-shadow ((t (:foreground "yellow"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "Firebrick4"))))
     (flymake-warnline ((t (:background "DarkBlue"))))
     (font-lock-builtin-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:foreground "yellow"))))
     (font-lock-comment-face ((t (:foreground "yellow"))))
     (font-lock-constant-face ((t (:foreground "magenta"))))
     (font-lock-doc-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "cyan" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:bold t :weight bold :foreground "blue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "green"))))
     (font-lock-type-face ((t (:foreground "green"))))
     (font-lock-variable-name-face ((t (:foreground "yellow" :weight light))))
     (font-lock-warning-face ((t (:foreground "red"))))
     (fringe ((t (:background "grey10"))))
     (git-gutter-fr:added ((t (:bold t :foreground "green" :weight bold))))
     (git-gutter-fr:deleted ((t (:bold t :foreground "red" :weight bold))))
     (git-gutter-fr:modified ((t (:bold t :foreground "magenta" :weight bold))))
     (git-gutter:added ((t (:bold t :foreground "green" :weight bold))))
     (git-gutter:deleted ((t (:bold t :foreground "red" :weight bold))))
     (git-gutter:modified ((t (:bold t :foreground "magenta" :weight bold))))
     (git-gutter:unchanged ((t (:background "yellow"))))
     (glyphless-char ((t (:underline t))))
     (header-line ((t (:underline t))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "green" :foreground "black"))))
     (hl-line ((t (:foreground "black" :background "green"))))
     (isearch ((t (:background "magenta4" :foreground "cyan1"))))
     (isearch-fail ((t (:background "red"))))
     (italic ((t (:underline t))))
     (lazy-highlight ((t (:background "turquoise3"))))
     (link ((t (:foreground "cyan" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (linum ((t (:foreground "yellow"))))
     (match ((t (:background "blue" :foreground "white"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (nil))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:foreground "black" :background "green"))))
     (mode-line-inactive ((t (nil))))
     (mouse ((t (nil))))
     (next-error ((t (:foreground "white" :background "blue"))))
     (nobreak-space ((t (:background "magenta"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (pp^L-highlight ((t (nil))))
     (query-replace ((t (:foreground "cyan1" :background "magenta4"))))
     (region ((t (:background "blue" :foreground "white"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "cyan" :foreground "black"))))
     (shadow ((t (:foreground "yellow"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (success ((t (:bold t :foreground "green" :weight bold))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "yellow"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
